### ISSUE TITLE
Proxmox 6.x?

### ISSUE THREAD

**Issue by Amplificator** [foundObjects/pve-nag-buster#2]
Does this still work with Proxmox 6.x?

**Comment by foundObjects** [comment]
It sure does!

**Comment by Amplificator** [comment]
Have you thought about using
`sed "s/NotFound/Active/g" /usr/share/perl5/PVE/API2/Subscription.pm`
to trick Proxmox into thinking it has a valid subscription?

**Comment by foundObjects** [comment]
Is there any benefit to doing that versus suppressing the nag popup?

**Comment by Amplificator** [comment]
From what I can tell it works on every version without the need of adjusting the path in case they decide, like they did previously with the method currently used by your tool.

**Comment by foundObjects** [comment]
For now I'm going to stay with the javascript method and reserve the subscription module patch as a backup in case it's ever needed.

Thanks for pointing this out, I'll play around with it a bit and make sure it doesn't break anything. Cheers!
